# Generated by Django 3.1.7 on 2021-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default=2, upload_to='bookcover/'),
            preserve_default=False,
        ),
    ]
