# Generated by Django 3.1.7 on 2021-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adminid',
            field=models.CharField(default=2, max_length=9),
            preserve_default=False,
        ),
    ]
